name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Oracle
        uses: docker/login-action@v3
        with:
          registry: iad.ocir.io
          username: idwwmbyiyhww/ldiaz@fusion.com.ar
          password: "]nK-0q]GGd+jt;h-UVX."
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: iad.ocir.io/idwwmbyiyhww/meta-ms-auth:latest
